[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
    "@uniswap/v3-core/contracts/=lib/v3-core/contracts/", 
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@wormhole-contracts/=lib/wormhole/ethereum/contracts/",
    "@scroll/contracts/=lib/scroll-contracts/src/"
    ]


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

 [etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
