[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/",
    "@uniswap/v3-core/contracts/=lib/v3-core/contracts/", 
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
    ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
